### ISSUE TITLE
TypeError: strptime() argument 1 must be str, not numpy.int64

### ISSUE THREAD

**Issue by aufawibowo** [nhancv/nc-csv2influxdb#1]
1. Did `git clone https://github.com/nhancv/nc-csv2influxdb`
2. The problem showed up
```
C:\Users\muhau\nc-csv2influxdb>
C:/ProgramData/Anaconda3/Scripts/activate
(base) C:\Users\muhau\nc-csv2influxdb>conda activate base
(base) C:\Users\muhau\nc-csv2influxdb>pip install progressbar
Collecting progressbar
  Downloading https://files.pythonhosted.org/packages/a3/a6/b8e451f6cff1c99b4747a2f7235aa904d2d49e8e1464e0b798272aa84358/progressbar-2.5.tar.gz
Building wheels for collected packages: progressbar
  Running setup.py bdist_wheel for progressbar ... done
  Stored in directory: C:\Users\muhau\AppData\Local\pip\Cache\wheels\c0\e9\6b\ea01090205e285175842339aa3b491adeb4015206cda272ff0
Successfully built progressbar
Installing collected packages: progressbar
Successfully installed progressbar-2.5

(base) C:\Users\muhau\nc-csv2influxdb>python csv2line.py -d retail1 -i data.csv -o import.txt
[===========================================================]Read csv file 100%
Traceback (most recent call last):                             ]Processing   0%
  File "csv2line.py", line 100, in <module>
    main(sys.argv[1:])
  File "csv2line.py", line 30, in main
    convert(dbname, inputfile, outputfile)
  File "csv2line.py", line 84, in convert
    + str(int(datetime.datetime.strptime(df_full["time"][d], "%Y-%m-%d %H:%M:%S").timestamp())*1000000000)
TypeError: strptime() argument 1 must be str, not numpy.int64

(base) C:\Users\muhau\nc-csv2influxdb>
```

**Comment by dayinjing** [comment]
Same, the data set it comes with doesn't work
